services:
  - type: web
    name: alko-api
    runtime: python
    buildCommand: pip install uv && uv sync
    startCommand: uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
